### ISSUE TITLE
General Instability with Rise Player on Raspberry Pi

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/player-raspberrypi#5]
### What is the expected behavior?

Rise Player should run without hitches on the Raspberry Pi

### What is the actual behavior?

Running Rise Player on the Raspberry Pi causes Rise Player and/or the Raspbian OS to crash

### What steps can be taken to replicate the problem?

1. Clone the rpi - 2017 Arts and rpi - 2017 Arts Flip presentations from my test company: https://apps.risevision.com/editor/list?cid=03579fe1-5639-46c3-a0e3-5434e776bc1b
2. Schedule both presentations to run on a Raspberry Pi Display

For me I had to leave the presentation running overnight and found that the OS was frozen and required a reboot the next morning.

**Comment by robb-price** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Issues related to new installer](https://trello.com/c/dbE4Llmv/7642-3-issues-related-to-new-installer)

**Comment by robb-price** [comment]
Since the next steps were discussed and will be followed through by Development, we are closing this issue.

**Comment by robb-price** [comment]
@santiagonoguez and I talked, we are opening this until the current RLS effort is rolled out, which contains the fix for this is rolled out. This shouldn't have been closed.

**Comment by robb-price** [comment]
Repo is not maintained. Closing this issue, and Alan will inform all when the release for memory management has been released.
